remote_theme: just-the-docs/just-the-docs

title: AI Dev Workflow CLI
description: Framework-agnostic tool for AI-guided development workflows
baseurl: "/ai-dev-workflow-cli"
url: "https://carmelyne.github.io"

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation
nav_external_links:
  - title: View on GitHub
    url: https://github.com/carmelyne/ai-dev-workflow-cli
    hide_icon: false

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/carmelyne/ai-dev-workflow-cli"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2023 AI Dev Workflow CLI Contributors. Distributed under an MIT license."
