# Workflow Composition Example
# Shows how to combine multiple workflow modules

workflows:
  # Core workflows (always included)
  core:
    - context/preservation
    - task/basic
  
  # Optional workflow groups
  team:
    - team/collaboration
    - context/sharing
    - task/team
  
  ml:
    - ml/experiment
    - ml/model-versioning
    - context/ml-enhanced
  
  enterprise:
    - team/compliance
    - context/audit
    - task/tracking

# Example compositions
examples:
  solo_developer:
    include:
      - core
    
  team_basic:
    include:
      - core
      - team
    
  ml_project:
    include:
      - core
      - ml
      - team
    
  enterprise:
    include:
      - core
      - team
      - enterprise

# Composition rules
rules:
  - "Core workflows are always included"
  - "Dependencies are automatically included"
  - "Conflicts are reported before composition"
  - "Later includes override earlier ones"
  - "Local customizations take precedence"
