project:
  name: "${project_name}"
  description: "${project_description}"
  repository: "${repository_url}"

workflows:
  0_context_persistence:
    description: "Simple context tracking for development sessions"
    context_management:
      storage:
        location: ".ai/context/"
        files:
          session: "current.yaml"     # Today's work
          knowledge: "knowledge.yaml"  # Important learnings
      
      # Quick commands to manage context
      user_controls:
        commands:
          - "ai keep 'item'"      # Keep important info
          - "ai tag 'item' '@decision'"  # Tag for organization
          - "ai search 'query'"   # Find past context
        
        # Quick way to mark important items
        tags:
          - "@decision"    # Design/technical decisions
          - "@important"   # Must-keep information
          - "@todo"       # Future work needed
      
      # Simple cleanup process
      cleanup:
        schedule: "weekly"
        notification: "3_days_before"
        process:
          - "Review flagged items"
          - "Keep or archive decisions"
          - "Clean old sessions"

  1_development:
    description: "Basic development workflow"
    steps:
      plan:
        - "Define task scope"
        - "List acceptance criteria"
      
      implement:
        - "Write code"
        - "Add tests"
        - "Update docs"
      
      review:
        - "Self-review changes"
        - "Run tests"
        - "Create PR"

# Extendable with features from master template
extensions_available:
  - "team_collaboration"
  - "advanced_retention"
  - "ml_features"
  - "compliance_rules"

# How to extend this config
help:
  extend_config: |
    To add more features, copy sections from config.master.yaml
    Example: To add team features, copy the 'team_collaboration' 
    section from master template.
  
  documentation: |
    Full features documented in config.master.yaml
    See examples/ directory for specific use cases
