# Default AI Workflow Configuration
version: "1.0.0"

project:
  name: "${project_name}"
  type: "${project_type}"
  description: "${project_description}"
  repository: "${repository_url}"

development_workflow:
  feature_development:
    steps:
      1_user_story:
        description: "Create user story in Gherkin format"
        location: "docs/stories/${feature_name}.md"
        template: |
          Feature: ${feature_name}
            As a ${user_type}
            I want ${desired_action}
            So that ${business_value}

            Scenario: ${scenario_name}
              Given ${precondition}
              When ${action}
              Then ${expected_result}

            Acceptance Criteria:
              - [ ] Criteria 1
              - [ ] Criteria 2

      2_branch_creation:
        description: "Create feature branch"
        command: "git checkout -b ${branch_type}/${feature_name}"
        branch_types:
          - "feature"
          - "bugfix"
          - "hotfix"
          - "refactor"

      3_documentation_first:
        description: "Update documentation with planned changes"
        files:
          - "docs/technical/${feature_name}.md"
          - "docs/api/${affected_endpoints}.md"
          - "README.md"

      4_implementation:
        description: "Implement the feature"
        guidelines:
          - "Follow project patterns"
          - "Write tests first"
          - "Update documentation"
          - "Consider performance"

      5_testing:
        description: "Add and run tests"
        types:
          - name: "unit"
            tool: "${test_framework}"
            coverage: 80
          - name: "integration"
            tool: "${test_framework}"
          - name: "e2e"
            tool: "${e2e_framework}"

      6_pr_creation:
        description: "Create pull request"
        template: |
          ## Changes
          ${changes_description}

          ## Testing
          - [ ] Unit tests
          - [ ] Integration tests
          - [ ] Manual testing

          ## Documentation
          - [ ] API docs updated
          - [ ] README updated
          - [ ] Migration guide added

patterns:
  - name: "documentation_first"
    description: "Write documentation before code"
    applies_to: ["all"]
    
  - name: "test_driven"
    description: "Write tests before implementation"
    applies_to: ["all"]
    
  - name: "clean_code"
    description: "Write maintainable, self-documenting code"
    applies_to: ["all"]
